# Built with Jekyll 3.2.0

# Setup
title:               'Margaret Cavendish:<br>Philosophical and Physical Opinions<br>(1663 edition)'
tagline:             'A digital edition'
description:         'A digital edition produced using the Ed/Jekyll theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
url:                 'http://idrhku.github.io'
baseurl:             '/cavendish'

# About/contact
author:
  name:              Alex Gil
  url:               https://twitter.com/elotroalex
  email:             colibri.alex@gmail.com

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: green

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
